name: MakeCode Arcade Release

on: 
  release:
    types:
      - created

jobs:
  build:
    runs-on: self-hosted
    # Setting the default shell for all steps in this job to PowerShell 7
    defaults:
      run:
        shell: pwsh

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MakeCode
        run: |
          npm install -g pxt
          pxt target arcade

      - name: Build JS
        run: |
          pxt clean
          pxt install
          pxt build --cloud

      - name: Build D51
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw samd51
          pxt build --hw samd51 --cloud
          Copy-Item ./built/binary.uf2 binary-d51.uf2

      - name: Build F4
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --cloud
          Copy-Item ./built/binary.uf2 binary-f4.uf2

      - name: Build P0
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw rpi
          pxt build --hw rpi --cloud
          Copy-Item ./built/binary.uf2 binary-p0.uf2

      - name: Bundle all
        # PowerShell 7 uses -AsByteStream instead of -Encoding Byte
        run: |
          Get-Content binary-*.uf2 -AsByteStream -Raw | Set-Content ./built/arcade.uf2 -AsByteStream

      - name: Upload bundled
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./built/arcade.uf2
          asset_name: arcade.uf2
          asset_content_type: application/octet-stream
